### PR TITLE
Fix/implement testing

### PR DESCRIPTION
**Pull request by roboli**
Hi there! Thanks a lot for this small library, has been useful. I noticed it doesn't have any tests implemented.

### CODE REVIEW

**Comment by igmonk** [comment]
Hi @roboli,
Appreciate your contribution, it's been a while since this project was properly tested last time 😉 

Any thoughts on why the images result in ~25Mb whereas their corresponding pdf files are less than 15Kb?

**Comment by roboli** [comment]
Actually, I generated those images using this same library :)  but I left the dpi param out so images were 300 dpi == 25Mb !

I changed that to 72 dpi and now they are ~1.4Mb. Seems that's how `ImageIOUtil` generates images right?

Cheers

**Comment by roboli** [comment]
So, it ocurred to me to convert the single PDF using this [site](https://www.pdfconvertonline.com/pdf-to-png-online.html) to PNG 72 dpi.

The generated file is 6.5Kb, that's a big difference. Probably we're missing something, I could take a look at this later. I'm using the library as it is and it's fine atm.

**Comment by igmonk** [comment]
@roboli that makes a lot of sense! Thanks for taking the time to look at this 👍

**Pull request merged**
